apiVersion: v1
kind: Service
metadata:
  name: hack-notification-service
  namespace: default
  labels:
    app: hack-notification-service
    service: notification-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: hack-notification-service

---
apiVersion: v1
kind: Service
metadata:
  name: hack-notification-service-headless
  namespace: default
  labels:
    app: hack-notification-service
    service: notification-service
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: hack-notification-service

---
# Optional: Ingress for external access to management endpoints
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hack-notification-service-ingress
  namespace: default
  labels:
    app: hack-notification-service
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    # Security annotations
    nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,192.168.0.0/16"
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
spec:
  rules:
  - host: hack-notification.local
    http:
      paths:
      - path: /actuator
        pathType: Prefix
        backend:
          service:
            name: hack-notification-service
            port:
              number: 8080
  # Uncomment for TLS
  # tls:
  # - hosts:
  #   - hack-notification.local
  #   secretName: hack-notification-tls

---
# Service Monitor for Prometheus (if using Prometheus Operator)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hack-notification-service-metrics
  namespace: default
  labels:
    app: hack-notification-service
    monitoring: prometheus
spec:
  selector:
    matchLabels:
      app: hack-notification-service
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 30s
    scrapeTimeout: 10s