spring:
  application:
    name: hack-vp-notification

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    consumer:
      group-id: ${KAFKA_GROUP_ID:notification-service}
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"

    listener:
      ack-mode: manual
      missing-topics-fatal: false
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}

management:
  health:
    kafka:
      enabled: false

notification:
  topics:
    videoFailed: ${TOPIC_VIDEO_FAILED:video.failed.v1}
    videoFailedDlq: ${TOPIC_VIDEO_FAILED_DLQ:video.failed.v1.dlq}

  retry:
    max-attempts: ${NOTIF_RETRY_MAX_ATTEMPTS:3}
    backoff-ms: ${NOTIF_RETRY_BACKOFF_MS:1000}

  email:
    from: ${NOTIF_EMAIL_FROM:no-reply@hack.local}
